version: '3'
services:

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
    - SECRET_KEY = ${SECRET_KEY}
    - ALGORITHM = ${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES = ${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
       - ./backend/:/app/backend
    depends_on:
      db:
        condition: service_healthy
    command: "uvicorn main:app --host 0.0.0.0 --reload"
  db:
    image: postgres
    ports:
      - 8090:8090
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_db"]
      interval: 1s
      timeout: 10s
      retries: 60
volumes:
  pgdata: